# **Feature Engineering notebook **

## Objectives

* Feature engineering and transformation of data
  * Encode categorical variables

## Inputs

outputs/datasets/cleaned/house_prices_cleaned.csv

## Outputs

outputs/datasets/cleaned/house_prices_encoded.csv

---

## Change working directory

In [1]:
import os
current_dir = os.getcwd()
current_dir

'/workspaces/heritage-housing-issues-milestone/jupyter_notebooks'

In [2]:
os.chdir(os.path.dirname(current_dir))
print("You set a new current directory")

You set a new current directory

In [3]:
current_dir = os.getcwd()
current_dir

'/workspaces/heritage-housing-issues-milestone'

## Load Cleaned Data

Train set:

In [4]:
import pandas as pd
train_set_path = "outputs/datasets/cleaned/train_set_cleaned.csv"
train_set = pd.read_csv(train_set_path)
train_set.head(3)

,1stFlrSF,2ndFlrSF,BedroomAbvGr,BsmtExposure,BsmtFinSF1,BsmtFinType1,BsmtUnfSF,GarageArea,GarageFinish,GarageYrBlt,...,LotArea,LotFrontage,MasVnrArea,OpenPorchSF,OverallCond,OverallQual,TotalBsmtSF,YearBuilt,YearRemodAdd,SalePrice
0,847,1112.0,4.0,Av,0,Unf,847,434,Fin,2004.0,...,11796,59.0,0.0,48.0,5,7,847,2004,2005,215000
1,1088,441.0,4.0,No,0,Unf,0,240,Unf,1945.0,...,8405,50.0,0.0,0.0,3,4,0,1945,1950,98000
2,1422,1177.0,4.0,No,0,Unf,1393,779,Fin,1999.0,...,14774,108.0,165.0,30.0,5,9,1393,1999,1999,333168

Test set:

In [5]:
test_set_path = 'outputs/datasets/cleaned/test_set_cleaned.csv'
test_set = pd.read_csv(test_set_path)
test_set.head(3)

,1stFlrSF,2ndFlrSF,BedroomAbvGr,BsmtExposure,BsmtFinSF1,BsmtFinType1,BsmtUnfSF,GarageArea,GarageFinish,GarageYrBlt,...,LotArea,LotFrontage,MasVnrArea,OpenPorchSF,OverallCond,OverallQual,TotalBsmtSF,YearBuilt,YearRemodAdd,SalePrice
0,920,866.0,3.0,Mn,486,GLQ,434,608,RFn,2001.0,...,11250,68.0,162.0,42.0,5,7,920,2001,2002,223500
1,1053,0.0,3.0,No,0,Unf,1053,648,RFn,2003.0,...,9375,75.0,768.0,45.0,5,8,1053,2003,2004,250000
2,988,0.0,3.0,No,827,Rec,161,572,Unf,1963.0,...,9945,69.0,57.0,0.0,5,5,988,1961,1961,128500

### Data Exploration

In [6]:
from ydata_profiling import ProfileReport
pandas_report = ProfileReport(df=train_set, minimal=True)
pandas_report.to_notebook_iframe()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

## Feature Engineering

### Encode Categorical Values

As in Notebook 2, we will encode categorical values to ensure compliance with algorithms.

In [7]:
from feature_engine.encoding import OrdinalEncoder


encoder = OrdinalEncoder(
    encoding_method='arbitrary',
    variables=['KitchenQual', 'BsmtExposure', 'BsmtFinType1', 'GarageFinish'],
    missing_values='ignore'
)

train_encoded = encoder.fit_transform(train_set)
test_encoded = encoder.fit_transform(test_set)
print(train_encoded.shape)
train_encoded.head(5)
print(test_encoded.shape)
test_encoded.head(5)

(1168, 22)
(292, 22)

/home/cistudent/.local/lib/python3.12/site-packages/feature_engine/encoding/base_encoder.py:223: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(X[feature]):
/home/cistudent/.local/lib/python3.12/site-packages/feature_engine/encoding/base_encoder.py:223: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(X[feature]):
/home/cistudent/.local/lib/python3.12/site-packages/feature_engine/encoding/base_encoder.py:223: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(X[feature]):
/home/cistudent/.local/lib/python3.12/site-packages/feature_engine/encoding/base_encoder.py:223: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(X[feature]):
/home/cistudent/.local/lib/python3.12/site-packages/feature_engine/encoding/base_encoder.py:223: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(X[feature]):
/home/cistudent/.local/lib/python3.12/site-packages/feature_engine/encoding/base_encoder.py:223: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(X[feature]):
/home/cistudent/.local/lib/python3.12/site-packages/feature_engine/encoding/base_encoder.py:223: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(X[feature]):
/home/cistudent/.local/lib/python3.12/site-packages/feature_engine/encoding/base_encoder.py:223: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(X[feature]):

,1stFlrSF,2ndFlrSF,BedroomAbvGr,BsmtExposure,BsmtFinSF1,BsmtFinType1,BsmtUnfSF,GarageArea,GarageFinish,GarageYrBlt,...,LotArea,LotFrontage,MasVnrArea,OpenPorchSF,OverallCond,OverallQual,TotalBsmtSF,YearBuilt,YearRemodAdd,SalePrice
0,920,866.0,3.0,0,486,0,434,608,0,2001.0,...,11250,68.0,162.0,42.0,5,7,920,2001,2002,223500
1,1053,0.0,3.0,1,0,1,1053,648,0,2003.0,...,9375,75.0,768.0,45.0,5,8,1053,2003,2004,250000
2,988,0.0,3.0,1,827,2,161,572,1,1963.0,...,9945,69.0,57.0,0.0,5,5,988,1961,1961,128500
3,845,0.0,2.0,1,565,3,280,360,1,1987.0,...,7599,69.0,0.0,0.0,6,4,845,1982,2006,129500
4,1234,1140.0,4.0,1,0,1,1181,656,2,2003.0,...,11999,93.0,340.0,100.0,5,8,1181,2003,2004,285000

---

# Push files to Repo

We will now save our cleaned data set

In [ ]:
# Check dataframe before saving
df.info()

In [ ]:
# Create collections folder and save cleaned dataset

df.to_csv('outputs/datasets/cleaned/house_prices_encoded.csv', index=False)